export const letterScores = [
  { letter: "a", score: 1 },
  { letter: "b", score: 3 },
  { letter: "c", score: 3 },
  { letter: "d", score: 2 },
  { letter: "e", score: 1 },
  { letter: "f", score: 4 },
  { letter: "g", score: 2 },
  { letter: "h", score: 4 },
  { letter: "i", score: 1 },
  { letter: "j", score: 8 },
  { letter: "k", score: 5 },
  { letter: "l", score: 1 },
  { letter: "m", score: 3 },
  { letter: "n", score: 1 },
  { letter: "o", score: 1 },
  { letter: "p", score: 3 },
  { letter: "q", score: 10 },
  { letter: "r", score: 1 },
  { letter: "s", score: 1 },
  { letter: "t", score: 1 },
  { letter: "u", score: 1 },
  { letter: "v", score: 4 },
  { letter: "w", score: 4 },
  { letter: "x", score: 8 },
  { letter: "y", score: 4 },
  { letter: "z", score: 10 },
] as const;
